### ISSUE TITLE
BRAT Project Error on DEM layer

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#143]
@banderson1618 

I'm getting the following error when running the BRAT Project tool.  I'm running 10.6.1.  I tried changing the layer files to the '10_6' version where relevant but still ran into the same error.  I ran this on the East Walker (TNC BRAT project) if you want to test with that basin on your end.

```Executing: BRAT_project_tool C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\BRATTest C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\LANDFIRE\LANDFIRE_140EVT.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\LANDFIRE\LANDFIRE_140BPS.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\NHD\NHD_24k_300mReaches.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\DEM\NED_DEM_10m.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\LANDFIRE\LANDFIRE_140EVT.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\VBET\BatchRun_01\02_Analyses\Output_1\ValleyBottom.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\RoadsRails\tl_2017_county_roads.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\RoadsRails\tl_2017_rails.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\NHD\NHDCanals.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\00_BRATTest\LandOwnership\NationalSurfaceManagementAgency.shp
Start Time: Wed Aug 15 10:34:08 2018
Running script BRAT_project_tool...

Traceback (most recent call last):
  File "<string>", line 156, in execute
  File "C:\etal\LocalCode\pyBRAT\BRATProject.py", line 83, in main
    makeTopoLayers(topoFolder)
  File "C:\etal\LocalCode\pyBRAT\BRATProject.py", line 158, in makeTopoLayers
    layers.append(makeLayer(demFolderPath, demFile, "DEM", demSymbology, isRaster=True))
  File "C:\etal\LocalCode\pyBRAT\BRATProject.py", line 196, in makeLayer
    raise arcpy.ExecuteError(err)
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000860: Output raster layer name: is not the type of Raster Layer, or does not exist.
Failed to execute (MakeRasterLayer).


Failed to execute (BRAT_project_tool).
Failed at Wed Aug 15 10:34:24 2018 (Elapsed Time: 16.45 seconds)

**Comment by banderson1618** [comment]
Could you link to the dataset that caused this problem? I haven't seen the error with any of the DEMs I've run, and I want to be sure it's the same one that caused the problem for you.

**Comment by bangen** [comment]
Here's a [Box link](https://usu.box.com/s/ha43nswq88tzcodqkq9f914d9ysk87bg) to the East Walker data.  The DEM is under the 'DEM' folder.  Since I had been working off BRAT on the master branch it's possible you had made changes already that remedied the issue?

**Comment by banderson1618** [comment]
@bangen, I can't replicate your problem, unfortunately. I've ran it on the master branch, and had no problems copying over the DEM you linked.

Based on the error text, it looks like there was some problem with the layer name. I'm just spitballing here, but maybe the error was caused by you having a layer named "DEM" in your table of contents, and then the tool freaked out when you tried to make another layer named "DEM"? I've known things like that to be a bit finicky in the past. I tried to recreate that, but it just removed the layer named DEM from my ToC instead of crashing. Might be a versioning thing.
