### ISSUE TITLE
BRAT Issue with ArcGIS Toolbox Python Scripts

### ISSUE THREAD

**Issue by bcking00** [Riverscapes/pyBRAT#296]
We are having issues getting the BRAT ArcGIS Python scripts into the ArcToolBox.  There is a red X over the tool.  Our network license is not setup for borrow and return.  Could this be the issue?  Any assistance will be much appreciated.  We are using ArcGIS 10.4.1.  Brian

**Comment by mhallerud** [comment]
Hi @bcking00, apologies for the belated response. The newest version of BRAT requires an additional library called xlsxwriter. This can be downloaded similarly to scikit-fuzzy ([see here for instructions](http://brat.riverscapes.xyz/Documentation/Download/ComputerSetup)), with `pip install xlsxwriter` in CMD. The current version of BRAT was developed using ArcGIS 10.6.1 which may lead to some issues. If you continue to have issues, you can tag my name in a reply here using "@mhallerud" so that I get a notification.

**Comment by mmayfieldtu** [comment]
Hello- I'm having trouble setting up a BRAT project. Similar to the user above I'm getting the red X over the toolbox after completing all of the setup steps described for scikit-fuzzy, numpy+MKL, xslxwriter, etc. One exception: when I attempt to install numpy+MKL 32-bit version, I get the following error:

> ERROR: numpy-1.16.6+mkl-cp27-cp27m-win32.whl is not a supported wheel on this platform.

I am able to successfully install a 64-bit version.

When using 'Check Syntax' on the BRAT toolbox, initially the error reported is 'No module named networkx'. Deviating from the recommended workflow, if I paste a copy of the networkx folder into the same folder with the BRAT tool, the resulting syntax error is 'No module named skfuzzy'. Paste the skfuzzy folder into the BRAT directory, and the syntax error becomes the following:

> Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\Users\Matthew.Mayfield\OneDrive - Trout Unlimited\ProjectWork\Misc\BRAT\pyBRAT-3.1.00\Veg_FIS.py", line 14, in <module>
    from skfuzzy import control as ctrl
  File "C:\Python27\Lib\site-packages\pyBRAT-3.1.00\skfuzzy\control\__init__.py", line 15, in <module>
    from .antecedent_consequent import (Antecedent, Consequent,
  File "C:\Python27\Lib\site-packages\pyBRAT-3.1.00\skfuzzy\control\antecedent_consequent.py", line 5, in <module>
    import networkx as nx
  File "C:\Users\Matthew.Mayfield\OneDrive - Trout Unlimited\ProjectWork\Misc\BRAT\pyBRAT-3.1.00\networkx\__init__.py", line 43, in <module>
    from networkx import release
ImportError: cannot import name release

Any help would be greatly appreciated-
Matt

**Comment by mmayfieldtu** [comment]
Update: I was running 64-bit python 2.7. I'm not yet successfully running BRAT, but the above errors are now moot and I'm working through the new ones. 

Thanks-
Matt

**Comment by joewheaton** [comment]
Hi Matt, Thanks for posting your progress here. Getting pyBRAT to run is a
pain in the ass, period. Sorry not to sugar coat it. The algorithms are
robust, but "getting it to work" is an exercise in advanced geoprocessing
and python troubleshooting. Annoying. The reason is it is a research-grade
tool that is coded up in arcPy, which is highly version
dependent/sensitive, and then has a bunch of open source python
dependencies (
http://brat.riverscapes.xyz/Documentation/Status/Tool_ReportCard_3-1-00).
We are not supporting helping people with troubleshooting this as it is a
ton of effort (and we have no funding/time to do that). It's free and you
get what you pay for, but it is not easy. This is precisely why we're
seeking funds to move these tools to professional grade or commercial grade
tools that are easier to run locally or can be run in the cloud and we
don't have to make sure the local dependencies are all sorted (e.g.
https://github.com/Riverscapes/sqlBRAT  ). Anyhow, I wish I had better
news, but for now that's the state of play ;). I hope you get it to run
(many have...) and I appreciate you posting your progress for others to use
for troubleshooting. I hope to make your problem obsolete in due course.

Best Wishes,
Joe
_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org
